name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test 1
      id: test-1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 1
        setup-command: g++ Lab8.cpp -o Lab8
        command: "./Lab8"
        input: '7'
        expected-output: 7 factorial is equal to 5040
        comparison-method: contains
        timeout: 1
    - name: Test 2
      id: test-2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 2
        setup-command: g++ Lab8.cpp -o Lab8
        command: "./Lab8"
        input: '8'
        expected-output: 8 factorial is equal to 40320
        comparison-method: contains
        timeout: 1
    - name: Test 3
      id: test-3
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 3
        setup-command: g++ Lab8.cpp -o Lab8
        command: "./Lab8"
        input: '5'
        expected-output: 5 factorial is equal to 120
        comparison-method: contains
        timeout: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-1_RESULTS: "${{steps.test-1.outputs.result}}"
        TEST-2_RESULTS: "${{steps.test-2.outputs.result}}"
        TEST-3_RESULTS: "${{steps.test-3.outputs.result}}"
      with:
        runners: test-1,test-2,test-3
